spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.employeems.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true